<a href="https://colab.research.google.com/github/weleba77/machine-Leaning-/blob/main/DSexaples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

Crating a dataframe from an  array

In [ ]:
data = np.array([[1,3],[3,6],[5,3]])

In [ ]:
df = pd.DataFrame(data,index= ['row1','row2','row3'] , columns=['col1', 'col2'])

In [ ]:
df

      col1  col2
row1     1     3
row2     3     6
row3     5     3

Crating a dataframe from adictionary

In [ ]:
states = ['california', 'Texas', 'Florida', 'New York']
population = [396139,29730311, 21944577, 19299981]

In [ ]:
dict_states = {
    'States': states,
    'Population': population
               }

In [ ]:
df_population = pd.DataFrame(dict_states)

In [ ]:
df_population

       States  Population
0  california      396139
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

Crating a dataframe from csv

In [ ]:
df_exams=pd.read_csv('student-por.csv',sep=";")

In [ ]:
df_exams.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
df_exams.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13

In [ ]:
df_exams.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
df_exams.tail(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
639,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
640,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
641,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
642,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
643,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
df_exams.shape

(649, 33)

In [ ]:
pd.set_option('display.max_row',1000)
df_exams

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,2,14,14,14
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,0,10,12,13
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,0,12,13,12
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,0,12,12,13
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,14,15
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,6,17,17,17
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,10,13,13,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,2,13,14,14
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,2,8,8,7
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,6,12,12,12
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,12,13,14
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,11,12,12
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,0,12,13,14
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,2,10,10,10
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,11,10
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,6,10,11,12
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,8,11,12,12
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,0,11,11,11
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,2,12,12,13
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,4,12,11,12
30,GP,M,15,U,GT3,T,4,4,health,services,...,5,4,2,3,4,5,0,10,11,11
31,GP,M,15,U,GT3,T,4,4,services,services,...,4,3,1,1,1,5,2,15,15,15
32,GP,M,15,R,GT3,T,4,3,teacher,at_home,...,4,5,2,1,1,5,0,13,14,15
33,GP,M,15,U,LE3,T,3,3,other,other,...,5,3,2,1,1,2,0,13,12,12
34,GP,M,16,U,GT3,T,3,2,other,other,...,5,4,3,1,1,5,4,12,12,12
35,GP,F,15,U,GT3,T,2,3,other,other,...,3,5,1,1,1,5,4,11,11,11
36,GP,M,15,U,LE3,T,4,3,teacher,services,...,5,4,3,1,1,4,0,14,14,14
37,GP,M,16,R,GT3,A,4,4,other,teacher,...,2,4,3,1,1,5,4,13,13,13
38,GP,F,15,R,GT3,T,3,4,services,health,...,4,3,2,1,1,5,2,11,12,12
39,GP,F,15,R,GT3,T,2,2,at_home,other,...,4,3,1,1,1,2,8,14,13,12
40,GP,F,16,U,LE3,T,2,2,other,other,...,3,3,3,1,2,3,16,11,11,10
41,GP,M,15,U,LE3,T,4,4,teacher,other,...,5,4,3,2,4,5,8,10,11,11
42,GP,M,15,U,GT3,T,4,4,services,teacher,...,4,3,3,1,1,5,0,14,15,15
43,GP,M,15,U,GT3,T,2,2,services,services,...,5,4,1,1,1,1,0,9,10,10
44,GP,F,16,U,LE3,T,2,2,other,at_home,...,4,3,3,2,2,5,14,10,11,11
45,GP,F,15,U,LE3,A,4,3,other,other,...,5,2,2,1,1,5,4,10,11,11
46,GP,F,16,U,LE3,A,3,3,other,services,...,2,3,5,1,4,3,6,13,12,13
47,GP,M,16,U,GT3,T,4,3,health,services,...,4,2,2,1,1,2,2,17,17,17
48,GP,M,15,U,GT3,T,4,2,teacher,other,...,4,3,3,2,2,5,4,11,12,13
49,GP,F,15,U,GT3,T,4,4,services,teacher,...,4,4,4,1,1,3,2,13,12,12
50,GP,F,16,U,LE3,T,2,2,services,services,...,4,3,3,2,3,4,0,14,13,13
51,GP,F,15,U,LE3,T,4,2,health,other,...,4,3,3,1,1,5,0,16,14,16
52,GP,M,15,U,LE3,A,4,2,health,health,...,5,5,5,3,4,5,4,10,9,9
53,GP,F,15,U,GT3,T,4,4,services,services,...,3,3,4,2,3,5,0,13,12,12
54,GP,F,15,U,LE3,A,3,3,other,other,...,5,3,4,4,4,1,0,13,12,13
55,GP,F,16,U,GT3,A,2,1,other,other,...,5,3,4,1,1,2,2,12,13,12
56,GP,F,15,U,GT3,A,4,3,services,services,...,4,3,2,1,1,1,0,15,14,15
57,GP,M,15,U,GT3,T,4,4,teacher,health,...,3,2,2,1,1,5,8,15,15,16
58,GP,M,15,U,LE3,T,1,2,other,at_home,...,4,3,2,1,1,5,0,14,13,14
59,GP,F,16,U,GT3,T,4,2,services,other,...,4,2,3,1,1,5,2,16,15,16
60,GP,F,16,R,GT3,T,4,4,health,teacher,...,2,4,4,2,3,4,0,17,16,16
61,GP,F,16,U,GT3,T,1,1,services,services,...,5,5,5,5,5,5,0,10,10,16
62,GP,F,16,U,LE3,T,1,2,other,services,...,4,4,3,1,1,1,0,13,13,10
63,GP,F,16,U,GT3,T,4,3,teacher,health,...,3,4,4,2,4,4,0,14,13,13
64,GP,F,15,U,LE3,T,4,3,services,services,...,4,4,4,2,4,2,0,13,12,12
65,GP,F,16,U,LE3,T,4,3,teacher,services,...,5,4,3,1,2,1,2,16,15,16
66,GP,M,15,U,GT3,A,4,4,other,services,...,1,3,3,5,5,3,0,11,12,12
67,GP,F,16,U,GT3,T,3,1,services,other,...,4,3,3,1,2,5,0,10,9,10
68,GP,F,15,R,LE3,T,2,2,health,services,...,4,1,3,1,3,4,0,11,10,11
69,GP,F,15,R,LE3,T,3,1,other,other,...,4,4,2,2,3,3,6,15,15,15
70,GP,M,16,U,GT3,T,3,1,other,other,...,4,3,2,1,1,5,2,13,11,11
71,GP,M,15,U,GT3,T,4,2,other,other,...,3,3,3,1,1,3,0,11,9,10
72,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,13,11,11
73,GP,M,16,U,GT3,T,3,1,other,other,...,5,3,2,2,2,5,0,13,13,14
74,GP,F,16,U,GT3,T,3,3,other,services,...,4,3,3,2,4,5,4,11,11,11
75,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,3,3,2,3,5,0,11,11,11
76,GP,M,15,U,GT3,T,4,0,teacher,other,...,3,4,3,1,1,1,0,12,11,11
77,GP,F,16,U,GT3,T,2,2,other,other,...,5,2,3,1,3,3,1,13,13,13
78,GP,M,17,U,GT3,T,2,1,other,other,...,4,5,1,1,1,3,0,9,9,10
79,GP,F,16,U,GT3,T,3,4,at_home,other,...,2,4,3,1,2,3,14,12,11,11
80,GP,M,15,U,GT3,T,2,3,other,services,...,3,2,2,1,3,3,0,11,11,12
81,GP,M,15,U,GT3,T,2,3,other,other,...,5,3,2,1,2,5,2,10,9,9
82,GP,F,15,U,LE3,T,3,2,services,other,...,4,4,4,1,1,5,4,12,11,11
83,GP,M,15,U,LE3,T,2,2,services,services,...,5,3,3,1,3,4,2,13,12,13
84,GP,F,15,U,GT3,T,1,1,other,other,...,4,3,2,2,3,4,2,13,12,12
85,GP,F,15,U,GT3,T,4,4,services,services,...,4,4,4,2,3,5,4,12,11,12
86,GP,F,16,U,LE3,T,2,2,at_home,other,...,4,3,4,1,2,2,6,13,11,11
87,GP,F,15,U,GT3,T,4,2,other,other,...,5,3,3,1,3,1,4,15,15,15
88,GP,M,16,U,GT3,T,2,2,services,other,...,4,4,2,1,1,3,6,12,10,11
89,GP,M,16,U,LE3,A,4,4,teacher,health,...,4,1,3,3,5,5,6,9,9,10
90,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,3,1,3,4,2,9,11,11
91,GP,F,15,U,GT3,T,4,3,services,other,...,4,5,5,1,3,1,6,14,13,13
92,GP,F,16,U,LE3,T,3,1,other,other,...,3,3,3,2,3,2,0,12,13,12
93,GP,F,16,U,GT3,T,4,2,teacher,services,...,5,3,3,1,1,1,2,13,14,14
94,GP,M,15,U,LE3,T,2,2,services,health,...,4,3,4,1,1,4,2,11,12,12
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,4,13,13,13
96,GP,M,16,R,GT3,T,4,3,services,other,...,3,3,3,1,1,4,6,9,11,11
97,GP,F,16,U,GT3,T,2,1,other,other,...,4,3,5,1,1,5,0,13,12,12
98,GP,F,16,U,GT3,T,4,4,other,other,...,5,3,4,1,2,1,4,12,13,13
99,GP,F,16,U,GT3,T,4,3,other,at_home,...,5,3,5,1,1,3,2,12,13,13
100,GP,M,16,U,GT3,T,4,4,services,services,...,4,5,5,5,5,4,12,9,9,8
101,GP,M,16,U,GT3,T,4,4,services,teacher,...,4,4,3,1,1,4,0,16,16,16
102,GP,M,15,U,GT3,T,4,4,services,other,...,5,3,3,1,1,5,2,12,13,12
103,GP,F,15,U,GT3,T,3,2,services,other,...,4,3,5,1,1,2,16,11,10,10
104,GP,M,15,U,GT3,A,3,4,services,other,...,5,4,4,1,1,1,0,16,16,16
105,GP,F,15,U,GT3,A,3,3,other,health,...,4,3,3,1,1,4,10,10,10,10
106,GP,F,15,U,GT3,T,2,2,other,other,...,5,1,2,1,1,3,4,10,10,10
107,GP,M,16,U,GT3,T,3,3,services,other,...,5,3,3,1,1,5,4,13,14,14
108,GP,M,15,R,GT3,T,4,4,other,other,...,1,3,5,3,5,1,8,12,10,11
109,GP,F,16,U,LE3,T,4,4,health,health,...,5,4,5,1,1,4,2,15,15,14
110,GP,M,15,U,LE3,A,4,4,teacher,teacher,...,5,5,3,1,1,4,4,13,14,14
111,GP,F,16,R,GT3,T,3,3,services,other,...,4,1,2,1,1,2,4,11,11,11
112,GP,F,16,U,GT3,T,2,2,at_home,other,...,3,1,2,1,1,5,12,8,10,10
113,GP,M,15,U,LE3,T,4,2,teacher,other,...,3,5,2,1,1,3,10,18,17,18
114,GP,M,15,R,GT3,T,2,1,health,services,...,5,4,2,1,1,5,4,10,9,10
115,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,5,4,4,1,2,5,6,16,14,14
116,GP,M,15,U,GT3,T,4,4,other,teacher,...,4,4,3,1,1,2,4,16,15,16
117,GP,M,16,U,GT3,T,3,3,other,services,...,5,4,2,1,1,5,6,14,14,15
118,GP,M,17,R,GT3,T,1,3,other,other,...,5,2,4,1,4,5,14,12,11,11
119,GP,M,15,U,GT3,T,3,4,other,other,...,3,4,3,1,2,4,2,14,13,14
120,GP,F,15,U,GT3,T,1,2,at_home,services,...,3,2,3,1,2,1,0,14,14,14
121,GP,M,15,U,GT3,T,2,2,services,services,...,5,5,4,1,2,5,6,14,13,13
122,GP,F,16,U,LE3,T,2,4,other,health,...,4,2,2,1,2,5,2,14,12,13
123,GP,M,16,U,GT3,T,4,4,health,other,...,3,4,4,1,4,5,4,12,13,13
124,GP,F,16,U,GT3,T,2,2,other,other,...,5,4,4,1,1,5,0,12,11,11
125,GP,M,15,U,GT3,T,3,4,services,services,...,5,5,5,3,2,5,2,9,9,9
126,GP,F,15,U,LE3,A,3,4,other,other,...,5,3,2,1,1,1,0,10,11,11
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,0,9,10,11
128,GP,M,16,R,GT3,T,4,4,teacher,teacher,...,3,5,5,2,5,4,8,14,14,15
129,GP,M,16,U,GT3,T,2,3,other,other,...,3,2,3,2,2,1,4,13,12,13
130,GP,F,15,R,GT3,T,3,4,services,teacher,...,4,2,2,2,2,5,0,10,11,12
131,GP,F,18,U,GT3,T,2,1,services,other,...,5,4,5,1,3,5,10,10,9,8
132,GP,F,17,U,LE3,A,2,1,other,other,...,3,2,2,1,2,5,8,11,10,11
133,GP,F,15,U,GT3,T,1,1,at_home,other,...,4,3,3,1,2,4,6,11,12,13
134,GP,F,17,U,LE3,T,2,2,other,other,...,3,4,4,1,3,5,2,13,12,12
135,GP,F,16,U,GT3,A,3,4,services,other,...,3,2,1,1,4,5,12,15,13,14
136,GP,M,16,U,GT3,T,2,1,at_home,other,...,3,2,1,1,1,2,4,9,9,11
137,GP,F,16,U,GT3,A,2,2,other,other,...,5,3,4,1,1,5,12,13,11,11
138,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,2,12,11,11
139,GP,F,15,U,GT3,T,4,4,services,at_home,...,4,3,3,1,1,5,4,13,14,15
140,GP,M,17,R,GT3,T,3,4,at_home,other,...,5,4,5,2,4,5,2,10,9,10
141,GP,F,16,R,GT3,T,1,1,at_home,other,...,5,1,3,1,1,3,0,14,13,13
142,GP,M,18,U,LE3,T,3,1,services,services,...,3,3,4,4,5,4,2,11,11,12
143,GP,F,18,U,GT3,A,3,2,other,services,...,4,3,3,5,1,5,10,12,11,11
144,GP,F,16,R,GT3,T,1,1,other,services,...,3,3,3,1,2,1,8,12,11,11
145,GP,F,16,U,GT3,A,3,3,other,other,...,4,3,2,1,1,5,4,9,9,10
146,GP,M,16,U,LE3,T,1,1,services,other,...,4,4,4,1,3,5,0,10,10,10
147,GP,F,15,U,GT3,T,4,4,teacher,teacher,...,4,3,2,1,1,5,6,13,14,14
148,GP,F,15,R,GT3,T,1,1,other,other,...,5,5,5,1,1,1,2,8,9,9
149,GP,M,15,U,GT3,T,4,3,teacher,services,...,2,2,2,1,1,3,6,9,11,11
150,GP,F,15,U,GT3,A,3,3,services,services,...,1,3,2,2,3,1,24,9,8,9
151,GP,M,16,U,GT3,T,4,4,services,services,...,5,3,3,1,3,5,0,15,13,13
152,GP,M,16,U,LE3,T,2,2,services,services,...,2,3,3,2,2,2,4,12,11,11
153,GP,F,15,U,GT3,T,4,4,teacher,services,...,4,2,2,1,1,5,2,13,13,13
154,GP,F,16,U,LE3,T,1,1,at_home,at_home,...,3,4,4,3,3,1,4,10,11,11
155,GP,M,17,U,GT3,T,2,1,other,other,...,5,4,5,1,2,5,22,9,7,6
156,GP,F,15,U,GT3,T,1,1,other,services,...,4,4,2,1,2,5,0,12,12,12
157,GP,F,15,U,LE3,A,2,1,at_home,other,...,4,4,2,1,1,5,0,11,10,10
158,GP,F,15,U,GT3,T,3,2,health,services,...,3,3,2,1,1,3,2,11,11,11
159,GP,F,15,U,GT3,T,1,2,at_home,other,...,4,3,2,1,1,5,6,13,12,13
160,GP,F,15,U,GT3,T,1,2,at_home,services,...,2,3,4,2,4,1,6,11,11,11
161,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,3,3,2,2,1,5,16,9,9,8
162,GP,M,15,U,LE3,A,2,1,services,other,...,4,5,5,2,5,5,0,12,11,11
163,GP,M,18,U,LE3,T,1,1,other,other,...,2,3,5,2,5,4,0,11,9,0
164,GP,M,16,U,LE3,T,2,1,at_home,other,...,4,4,4,3,5,5,6,9,10,10
165,GP,F,15,R,GT3,T,3,3,services,services,...,4,2,1,2,3,3,2,13,13,13
166,GP,M,19,U,GT3,T,3,2,services,at_home,...,4,5,4,1,1,4,6,11,9,11
167,GP,F,17,U,GT3,T,4,4,other,teacher,...,4,2,1,1,1,4,0,13,13,13
168,GP,M,15,R,GT3,T,2,3,at_home,services,...,4,4,4,1,1,1,0,7,8,8
169,GP,M,17,R,LE3,T,1,2,other,other,...,2,2,2,3,3,5,14,9,8,10
170,GP,F,18,R,GT3,T,1,1,at_home,other,...,5,2,5,1,5,4,6,11,10,11
171,GP,M,16,R,GT3,T,2,2,at_home,other,...,4,2,2,1,2,3,4,12,10,11
172,GP,M,16,U,GT3,T,3,3,other,services,...,4,5,5,4,4,5,0,10,10,1
173,GP,M,16,U,LE3,T,1,2,health,services,...,4,4,5,3,5,5,0,9,8,10
174,GP,M,17,R,LE3,T,2,1,at_home,other,...,3,3,2,2,2,5,8,8,8,9
175,GP,M,17,R,GT3,T,3,2,other,other,...,4,4,4,1,4,3,4,7,6,8
176,GP,M,15,U,LE3,T,1,2,other,other,...,4,4,4,2,4,5,2,8,9,10
177,GP,M,16,U,GT3,T,1,3,at_home,services,...,5,3,3,1,4,2,2,9,8,8
178,GP,M,17,R,LE3,T,1,1,other,services,...,5,3,5,1,5,5,0,8,8,8
179,GP,M,17,U,GT3,T,3,2,services,services,...,4,5,2,1,1,2,10,8,7,8
180,GP,M,16,U,GT3,T,2,2,other,other,...,4,3,5,2,4,4,0,9,10,11
181,GP,F,16,U,GT3,T,4,2,health,services,...,4,2,3,1,1,3,0,17,17,18
182,GP,F,16,U,GT3,T,2,2,other,other,...,5,1,5,1,1,4,0,12,12,13
183,GP,F,16,U,GT3,T,4,4,health,health,...,4,4,2,1,1,3,0,16,16,17
184,GP,M,16,U,GT3,T,3,4,other,other,...,3,4,5,2,4,2,4,9,9,10
185,GP,M,16,U,GT3,T,1,0,other,other,...,4,3,2,1,1,3,0,16,17,18
186,GP,M,17,U,LE3,T,4,4,teacher,other,...,4,4,4,1,3,5,0,11,9,10
187,GP,F,16,U,GT3,T,1,3,at_home,services,...,4,3,5,1,1,3,0,14,13,13
188,GP,F,16,U,LE3,T,3,3,other,other,...,4,4,5,1,1,4,0,14,14,15
189,GP,M,17,U,LE3,T,4,3,teacher,other,...,4,4,4,4,4,4,0,10,11,11
190,GP,F,16,U,GT3,T,2,2,services,other,...,3,4,4,1,4,5,0,13,12,14
191,GP,M,17,U,GT3,T,3,3,other,other,...,4,3,4,1,4,4,4,11,9,10
192,GP,M,16,R,GT3,T,4,2,teacher,services,...,4,3,3,3,4,3,8,10,9,11
193,GP,M,17,U,GT3,T,4,3,other,other,...,5,2,3,1,1,2,4,11,11,13
194,GP,M,16,U,GT3,T,4,3,teacher,other,...,3,4,3,2,3,3,4,11,10,11
195,GP,M,16,U,GT3,T,3,3,services,other,...,4,2,3,1,2,3,0,11,12,13
196,GP,F,17,U,GT3,T,2,4,services,services,...,5,4,2,2,3,5,0,17,18,17
197,GP,F,17,U,LE3,T,3,3,other,other,...,5,3,3,2,3,1,32,14,13,14
198,GP,F,16,U,GT3,T,3,2,other,other,...,1,2,2,1,2,1,8,14,15,16
199,GP,M,17,U,GT3,T,3,3,services,services,...,4,3,4,2,3,4,6,11,13,14
200,GP,M,16,U,GT3,T,1,2,services,services,...,3,3,3,1,2,3,0,10,9,11
201,GP,M,16,U,LE3,T,2,1,other,other,...,4,2,3,1,2,5,0,13,14,16
202,GP,F,17,U,GT3,A,3,3,health,other,...,3,3,3,1,3,3,10,12,13,14
203,GP,M,17,R,GT3,T,1,2,at_home,other,...,3,1,3,1,5,3,6,9,9,10
204,GP,F,16,U,GT3,T,2,3,services,services,...,4,3,3,1,1,2,6,12,12,13
205,GP,F,17,U,GT3,T,1,1,at_home,services,...,5,3,3,1,1,3,0,12,11,12
206,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,16,10,11,12
207,GP,M,16,R,GT3,T,3,3,services,services,...,4,3,2,3,4,5,0,11,10,10
208,GP,M,16,U,GT3,T,2,3,other,other,...,5,3,3,1,1,3,0,13,12,12
209,GP,F,17,U,LE3,T,2,4,services,services,...,4,3,2,1,1,5,8,14,15,16
210,GP,M,17,U,GT3,T,4,4,services,teacher,...,5,2,3,1,2,5,4,13,13,14
211,GP,M,16,R,LE3,T,3,3,teacher,other,...,3,3,4,3,5,3,16,10,11,12
212,GP,F,17,U,GT3,T,4,4,services,teacher,...,4,2,4,2,3,2,30,14,15,16
213,GP,F,16,U,LE3,T,4,4,teacher,teacher,...,4,5,2,1,2,3,0,11,10,11
214,GP,F,16,U,GT3,T,4,3,health,other,...,4,3,5,1,5,2,2,14,14,15
215,GP,F,16,U,GT3,T,2,3,other,other,...,4,4,3,1,3,4,4,11,12,12
216,GP,F,17,U,GT3,T,1,1,other,other,...,4,4,4,1,3,1,0,14,15,15
217,GP,F,17,R,GT3,T,2,2,other,other,...,5,3,2,1,2,3,21,13,13,13
218,GP,F,16,R,GT3,T,2,2,services,services,...,5,3,5,1,1,5,6,13,13,13
219,GP,F,17,U,GT3,T,3,4,at_home,services,...,4,4,3,3,4,5,14,8,9,8
220,GP,F,16,U,GT3,A,3,1,services,other,...,2,3,3,2,2,4,2,11,11,12
221,GP,F,16,U,GT3,T,4,3,teacher,other,...,1,3,2,1,1,1,4,14,15,15
222,GP,F,16,U,GT3,T,1,1,at_home,other,...,4,3,2,1,4,5,2,12,13,13
223,GP,F,17,R,GT3,T,4,3,teacher,other,...,4,4,2,1,1,4,0,11,12,12
224,GP,F,19,U,GT3,T,3,3,other,other,...,4,3,3,1,2,3,4,12,12,12
225,GP,M,17,U,LE3,T,4,4,services,other,...,5,3,5,4,5,3,15,13,12,12
226,GP,F,16,U,GT3,A,2,2,other,other,...,3,3,4,1,1,4,0,13,13,13
227,GP,M,18,U,GT3,T,2,2,services,other,...,4,4,4,2,4,5,10,12,11,11
228,GP,F,17,R,LE3,T,4,4,services,other,...,5,2,1,1,2,3,6,12,11,11
229,GP,F,17,U,LE3,T,3,2,other,other,...,4,4,4,1,3,1,2,14,16,15
230,GP,F,17,U,GT3,T,4,3,other,other,...,3,4,5,2,4,1,16,11,9,10
231,GP,M,18,U,LE3,T,3,3,services,health,...,3,2,4,2,4,4,10,10,10,10
232,GP,F,17,U,GT3,T,2,3,at_home,other,...,3,3,3,1,4,3,4,12,13,13
233,GP,F,17,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,1,4,0,12,12,13
234,GP,F,17,R,GT3,T,2,1,at_home,services,...,4,2,5,1,2,5,0,11,10,11
235,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,4,1,1,5,12,12,12,12
236,GP,F,16,U,GT3,T,2,3,services,teacher,...,2,3,1,1,1,3,0,13,13,14
237,GP,M,18,U,GT3,T,2,2,other,other,...,3,3,3,5,5,4,9,10,9,10
238,GP,F,16,U,GT3,T,4,4,teacher,services,...,5,3,2,1,1,5,4,15,16,16
239,GP,F,18,R,GT3,T,3,1,other,other,...,5,3,3,1,1,4,4,8,8,8
240,GP,F,17,U,GT3,T,3,2,other,other,...,5,3,4,1,3,3,2,17,18,17
241,GP,M,17,U,LE3,T,2,3,services,services,...,5,3,3,1,3,3,0,10,11,11
242,GP,M,18,U,LE3,T,2,1,at_home,other,...,4,3,2,4,5,3,2,9,10,11
243,GP,F,17,U,GT3,A,2,1,other,other,...,3,2,3,1,2,3,0,15,15,16
244,GP,F,17,U,LE3,T,4,3,health,other,...,3,2,3,1,2,3,0,14,12,12
245,GP,M,17,R,GT3,T,2,2,other,other,...,4,5,2,1,1,1,0,12,13,13
246,GP,M,17,U,GT3,T,4,4,teacher,teacher,...,4,5,5,1,3,2,0,13,13,13
247,GP,M,16,U,GT3,T,4,4,health,other,...,4,2,4,2,4,1,0,13,13,14
248,GP,M,16,U,LE3,T,1,1,other,other,...,3,4,2,1,1,5,2,9,9,9
249,GP,M,16,U,GT3,T,3,2,at_home,other,...,5,3,3,1,3,2,0,12,12,12
250,GP,M,17,U,LE3,T,2,2,other,other,...,4,4,2,5,5,4,0,16,16,16
251,GP,F,16,U,GT3,T,2,1,other,other,...,4,5,2,1,1,5,4,9,10,10
252,GP,F,16,U,GT3,A,4,1,other,other,...,5,3,3,1,2,5,0,14,13,13
253,GP,F,18,U,LE3,A,2,4,services,other,...,4,3,3,1,1,3,18,10,10,10
254,GP,F,18,U,LE3,T,2,2,at_home,services,...,5,3,1,1,1,5,16,9,8,10
255,GP,F,18,U,GT3,T,3,3,other,other,...,4,1,1,1,1,3,14,8,7,7
256,GP,M,18,U,GT3,T,2,2,other,at_home,...,4,4,3,2,2,1,26,7,8,8
257,GP,M,17,U,GT3,T,4,4,teacher,teacher,...,4,2,1,1,2,5,6,10,8,9
258,GP,F,17,U,GT3,T,3,2,other,other,...,5,4,2,1,1,3,4,14,14,15
259,GP,F,17,U,LE3,T,1,1,at_home,at_home,...,4,3,2,1,2,4,10,11,10,10
260,GP,F,16,U,GT3,T,1,2,other,other,...,5,3,5,1,2,5,4,12,11,11
261,GP,F,17,R,GT3,T,2,1,at_home,services,...,2,1,1,1,1,3,2,13,13,13
262,GP,F,17,R,LE3,A,1,4,other,other,...,5,5,4,1,1,5,14,9,9,8
263,GP,M,18,U,GT3,T,2,2,other,services,...,5,5,4,3,5,2,16,8,7,8
264,GP,F,17,U,LE3,A,2,2,other,other,...,3,1,2,1,1,1,8,11,9,10
265,GP,F,17,R,LE3,T,1,1,at_home,other,...,4,3,3,1,3,5,4,15,14,15
266,GP,F,17,U,LE3,A,4,2,teacher,other,...,4,3,2,1,1,4,4,15,14,14
267,GP,M,17,U,LE3,T,4,3,health,other,...,2,5,5,1,4,5,8,15,15,15
268,GP,M,17,R,LE3,A,4,4,teacher,other,...,3,3,3,2,3,4,0,12,12,12
269,GP,M,16,U,LE3,T,4,3,teacher,other,...,5,4,5,1,1,3,7,14,14,15
270,GP,M,16,U,GT3,T,4,4,services,services,...,5,3,2,1,2,5,4,14,15,15
271,GP,F,17,U,GT3,T,4,4,teacher,services,...,5,3,1,1,4,5,2,11,11,12
272,GP,M,17,R,GT3,T,1,1,other,other,...,4,3,3,1,1,1,2,13,14,15
273,GP,F,17,U,GT3,T,3,3,services,other,...,4,2,2,2,3,5,10,11,11,11
274,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,2,1,1,4,10,10,9,10
275,GP,F,18,U,GT3,T,2,1,other,other,...,4,4,4,1,1,3,10,12,10,11
276,GP,M,16,U,GT3,T,2,1,other,other,...,4,3,3,1,1,4,7,15,16,16
277,GP,F,17,U,GT3,T,1,1,other,services,...,4,3,4,1,2,5,4,11,10,11
278,GP,M,17,U,GT3,T,2,3,other,other,...,5,2,2,1,1,2,2,9,12,13
279,GP,M,22,U,GT3,T,3,1,services,services,...,5,4,5,5,5,1,12,7,8,5
280,GP,M,18,R,LE3,T,3,3,other,services,...,4,3,3,1,3,5,8,10,9,10
281,GP,M,16,U,GT3,T,0,2,other,other,...,4,3,2,2,4,5,0,11,12,11
282,GP,M,18,U,GT3,T,3,2,services,other,...,4,4,5,2,4,5,8,7,8,7
283,GP,M,16,U,GT3,T,3,3,at_home,other,...,5,3,3,1,3,2,4,9,11,10
284,GP,M,18,U,GT3,T,2,1,services,services,...,3,2,5,2,5,5,4,7,8,6
285,GP,M,16,R,GT3,T,2,1,other,other,...,3,3,2,1,3,3,2,14,13,12
286,GP,M,17,R,GT3,T,2,1,other,other,...,4,4,2,2,4,5,0,12,12,13
287,GP,M,17,U,LE3,T,1,1,health,other,...,4,4,4,1,2,5,0,9,10,10
288,GP,F,18,U,LE3,A,2,1,other,other,...,4,3,4,1,3,5,2,12,12,13
289,GP,F,17,U,LE3,T,4,2,teacher,services,...,4,2,3,1,1,4,2,14,15,17
290,GP,F,19,U,GT3,T,2,2,services,services,...,4,3,3,1,1,5,0,10,10,11
291,GP,M,18,U,LE3,T,2,1,services,other,...,4,4,5,4,4,5,4,11,10,11
292,GP,F,17,R,GT3,T,4,2,other,other,...,4,3,4,1,3,5,2,11,12,14
293,GP,F,18,U,LE3,T,1,1,other,at_home,...,4,4,3,2,3,3,4,11,12,14
294,GP,F,18,R,GT3,T,2,2,other,other,...,3,2,3,1,1,5,4,11,11,13
295,GP,M,19,U,LE3,A,4,3,services,at_home,...,4,3,1,1,1,1,4,11,13,14
296,GP,M,18,U,GT3,T,2,1,other,other,...,5,2,4,1,2,4,2,16,16,16
297,GP,M,17,R,GT3,T,2,2,other,services,...,5,2,2,1,1,4,0,9,10,10
298,GP,F,17,U,LE3,T,2,2,services,services,...,3,4,1,1,1,2,2,10,11,12
299,GP,F,20,R,GT3,T,2,1,other,other,...,1,2,3,1,2,2,8,10,12,12
300,GP,F,18,U,GT3,T,4,3,services,other,...,3,1,2,1,3,2,2,15,15,15
301,GP,M,18,U,GT3,T,4,3,teacher,other,...,4,3,2,1,1,3,2,10,10,11
302,GP,M,18,R,GT3,T,3,2,other,other,...,5,3,2,1,1,3,2,10,11,12
303,GP,F,17,U,GT3,T,3,3,other,other,...,3,2,3,1,1,4,2,15,12,13
304,GP,F,18,U,GT3,T,2,2,at_home,services,...,4,3,3,1,1,3,0,11,12,13
305,GP,M,17,U,GT3,T,2,2,other,other,...,4,4,4,2,3,4,8,8,8,9

Functions

In [ ]:
len(df_exams)

649

In [ ]:
max(df_exams.index)

648

In [ ]:
min(df_exams.index)

0

In [ ]:
type(df_exams)

pandas.core.frame.DataFrame

In [ ]:
pd.set_option('display.max_row',10)

In [ ]:
round(df_exams, 2)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
print(df_exams.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [ ]:
df_exams.sort_values(
    by=['freetime', 'Dalc', 'G1'],
    ascending=False,
    inplace=True
)
df_exams

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
61,GP,F,16,U,GT3,T,1,1,services,services,...,5,5,5,5,5,5,0,10,10,16
457,MS,M,17,R,LE3,T,1,2,at_home,services,...,5,5,5,5,5,3,4,10,11,11
100,GP,M,16,U,GT3,T,4,4,services,services,...,4,5,5,5,5,4,12,9,9,8
576,MS,M,18,R,GT3,T,3,2,other,other,...,2,5,5,5,5,5,8,9,10,11
447,MS,M,17,R,GT3,T,2,1,other,other,...,5,5,5,5,5,3,8,8,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,MS,F,17,R,GT3,T,2,2,at_home,other,...,5,1,3,1,2,5,5,9,9,9
112,GP,F,16,U,GT3,T,2,2,at_home,other,...,3,1,2,1,1,5,12,8,10,10
255,GP,F,18,U,GT3,T,3,3,other,other,...,4,1,1,1,1,3,14,8,7,7
513,MS,F,16,U,GT3,T,3,1,other,other,...,3,1,3,1,3,1,0,8,6,8
514,MS,F,16,U,GT3,T,3,2,services,at_home,...,3,1,3,1,4,3,2,7,6,7